### ISSUE TITLE
Multiple Item Blocks?

### ISSUE THREAD

**Issue by tkasci** [philchalmers/mirtCAT#12]
Is it possible to define multiple item blocks with different options of their respective items? I'd like to assess one questionnaire only on Sundays and they need to have a different input type.

**Comment by philchalmers** [comment]
Yes, just create your own `findNextItem` function and pass it to `mirtCAT(design=list(customNextItem=findNextItem))`. The item selection can be completely customized to your liking this way.

Also, please post questions to the forum rather than opening issues (https://groups.google.com/forum/#!forum/mirt-package). This outlet is primarily for bug tracking and feature requests.
