### ISSUE TITLE
MLE at infinity for a variable response pattern

### ISSUE THREAD

**Issue by jilljenn** [philchalmers/mirtCAT#14]
Hi,

Is this normal behavior?

    library(CDM) # For data
    data = fraction.subtraction.data

    library(mirt) # For training
    fit = mirt(data, 2)
    V <- coef(fit, simplify=TRUE)$items

Output:

                   a1          a2          d g u
    Item1  -2.9198130  3.53239933  0.1548285 0 1
    Item2  -6.2479459  7.37367588  1.2916350 0 1
    ...

Seems fine. But then:

    library(mirtCAT) # For testing
    CATdesign <- mirtCAT(NULL, fit, method='ML', criteria='Drule', start_item='Drule', local_pattern=data, design_elements=TRUE)
    CATdesign <- updateDesign(CATdesign, items=c(1), response=c(0))
    CATdesign$design@Update.thetas(CATdesign$design, CATdesign$person, CATdesign$test)
    CATdesign <- updateDesign(CATdesign, items=c(2), response=c(1))
    CATdesign$design@Update.thetas(CATdesign$design, CATdesign$person, CATdesign$test)
    CATdesign$person$thetas_history

I get:

                F1          F2
    [1,] 0.0000000    0.000000
    [2,] 0.3151363   -0.381255
    [3,]      -Inf -598.085780

How come? If I remove `method='ML'` I get a reasonable (`MAP`) estimate. But shouldn't the MLE exist for such a simple variable response pattern?

**Comment by philchalmers** [comment]
This is largely normal behaviour. You need sufficient variability in each dimension in order to compute ML estimates, (i.e., the likelihood functions need some type of curvature with a single mode). It's peculiar to me that `[2, ]` could be obtained though, because the `[2,] 0.3151363   -0.381255` estimates are clearly based on scores that haven't converged yet. I'll see if that can be patched, but otherwise this behaviour should be expected.
