### ISSUE TITLE
Shuffling in new questions into mirtCAT session

### ISSUE THREAD

**Issue by e-bartsch** [philchalmers/mirtCAT#15]
Is there a best way to shuffle in questions that were not fit in the mirt model into the mirt session? These questions would not be graded, and instead would be used in the mirt model later when sufficient data has been collected. It seems like using something like the `precat` argument in the mirtCAT model would not work since the questions are not part of the original mirt model

**Comment by philchalmers** [comment]
There is a `constraints$not_scored` input which you can use to indicate an item is not scored, only the responses are collected. Then, using some customized scheme laid out with a `findNextItem()` function you could still do an adaptive criteria, but manually add in whatever items you want data collected from. Because these are not scored, they are not used in the scoring of the latent trait parameters/SEs. 

With this approach you can give the 'dummy' items whatever parameters you want, because they play no part in the process. HTH.

**Comment by e-bartsch** [comment]
@philchalmers I am trying to use the `not_scored` constraint but it doesn't seem like I can use it with items that are not part of the `mirt` model passed into the `mirtCAT$mo` input. Is there a way to include items as `not_scored` in the `mirt` model so I can then mark them to be not scored?

Thanks for the help!

**Comment by philchalmers** [comment]
I don't mind answering this question, but would you mind posting it on the forum? Others may be interested in this topic as well.

**Comment by e-bartsch** [comment]
Thanks Phil, just posted here: https://groups.google.com/forum/#!topic/mirt-package/WPEGqX2EMUM
