### ISSUE TITLE
Outmessage customization/language support

### ISSUE THREAD

**Issue by dansom** [philchalmers/mirtCAT#19]
Hi Phil & all,

as already posted in the google group, I have a suggestion for the next version of the package:
Most parts of the mirtCAT GUI can be configured using the shinyGUI, for example title, authors, and instructions. This is very helpful is you want to run mirtCAT in a non english-speaking country. For some reason, this appears to not be the case for the outmessage "please provide a suitable response".

Thus my suggestion to add the outmessage to the customizable aspects in shinyGUI so that the outmessage can be adapted and mirtCAT would be entirely usable in other languages :-) 

Thanks in Advance,

Daniel

**Comment by philchalmers** [comment]
This is now possible by the new `shinyGUI$response_msg` input, but this type of request has many other instances in the package....too many to do quickly. If there are others that are very important then I'm happy to address them; otherwise, you can study the commit I just made and send a pull request with other areas that should be made modifiable as well. 

I'll close this for now as it addresses your problem, but more work on this topic could be made.

**Comment by dansom** [comment]
Hi Phil,
thanks a lot also for this quick change. If I stumble upon are any other instances of English messages that need to be customizable, I'll add an according pull request. The changes in the commit seem easy enough for me to handle ;-)
