### ISSUE TITLE
Next-Button on lastpage when stopApp = FALSE,

### ISSUE THREAD

**Issue by dansom** [philchalmers/mirtCAT#20]
Hi Phil & all,

I have another suggestion regarding the "next"-Button on the lastpage of a mirtCAT.
When hosting the mirtCAT on a remote server, you suggest the following for stopApp:

> when hosting an application on a remote server this should be set to `FALSE` to allow a more graceful completion (in which case the last page will be displayed until the browser tab is closed)

This is understandable and makes sense. However, with this configuration the lastpage of a mirtCAT stays up "forever" and the "next"-Button, which is displayed, is actually nonfunctional (as there is no next page). This is a bit confusing for users, as they may try to press "next" with nothing happening.

Thus I would recommend to hide the "next"-Button on the last page in this configuration. Alternatively it could also be greyed out, contain a (customizable) link to a website, or even a close-tab command.

Thanks in advance,
Daniel

**Comment by philchalmers** [comment]
Doesn't the last page default prompt users that the interface is complete and to close their browser/tab? I'd prefer to have some type of final page because otherwise the interface stopping abruptly would cause anxiety to some responders who were wondering whether everything was submitted okay....

Also, hiding the Next button is much easier said than done. Because mirtCAT relies on `shiny` there are a few components that seem to be hard coded, like the general structure of the interface (which the next button is part of). It likely is possible to grey-out the next button using something like the `shinyjs` package, though I have not tried it. In any case, it seems more aesthetic than functional, so probably will be low on the TODO list. 

I do like the idea of sending a 'close tab' command, but I'm not sure if `shiny` has the rights to do that (it's a bit abrasive), and HTML links can be added to the final splash message in case users should be redirected at their leisure.

**Comment by philchalmers** [comment]
Here's the current state of removing the `Next` button on the last page. Hopefully, folks at SO know what's going on enough to fix the core of my problem: https://stackoverflow.com/questions/52214594/remove-actionbutton-via-removeui-function-in-shiny

**Comment by philchalmers** [comment]
Fixed my own SO problem by using a `div()` call. Learned a few things along the way with this request. Hopefully, this new behaviour will cause less confusion. Here's what the default final page now looks like:

![screenshot 7](https://user-images.githubusercontent.com/1274464/45196915-9309d380-b22c-11e8-8959-41b67b851ed7.png)

**Comment by dansom** [comment]
Hi Phil,

that looks really great! Thanks for the quick work and the great result :-)
Regarding your very first comment:

> Doesn't the last page default prompt users that the interface is complete and to close their browser/tab? I'd prefer to have some type of final page because otherwise the interface stopping abruptly would cause anxiety to some responders who were wondering whether everything was submitted okay....

I use a custom last page to give participants feedback based on their answers. Thus, the "complete & close"-Message is not that prominent and only at the bottom of the page after the feedback. In contrast, the "next"-Button is located much more prominent, so that participants were a bit unsure about the next button.
Still, I agree with you that having a last page with some "the CAT is over"-message is definitely important so that participants know everything worked out.
-->Having the custom last page without the prominent "next" button now is great :-)

**Comment by philchalmers** [comment]
Gotcha. I'm inclined to agree that the "Next" button was largely silly on the last page and never should have been there at all. This was mainly my ignorance showing in that I knew more about IRT when I was first writing `mirtCAT` than the workings of `shiny`, and many of the server components I went with early on I now regret because of their difficulty in being extensible. Nevertheless, I still think `mirtCAT` is useful and unique, and maybe one day I'll go back and rewrite the server/UI components (maybe in a `mirtCAT2()` function to avoid deprecating functions). Cheers.
