### ISSUE TITLE
Feature request: Input answer on itemtimer end

### ISSUE THREAD

**Issue by MagnusNordmo** [philchalmers/mirtCAT#34]
Hi! 
After a lot of practical use I have observed that not all users understand the answer button functionality, even though this is clearly explained in an introduction. Some users inputs an answers and erroneously waits until the item timer runs out.A great solution to this is to have a logical input that controls the end of item-timer behaviour.

- T = selected item/written input is used as input when item timer runs out
- F = failure to press the answer button before item timer runs out results in wrong answer. 

I have tried to implement this myself but have not been successful. I cannot seem to understand how `mirtCAT` selects the answers provided by the user. My attempts either breaks the test or doesn't provide the answer. 

Thanks for `mirtCAT`! It really is terrific.

Sincerely
Magnus

**Comment by philchalmers** [comment]
Thanks for the suggestion, I'm not opposed to this idea. Should this be supported on a per-item basis (i.e., within the definition of the `data.frame` of questions, answers, ...) or as a global flag that should always be applied? I feel the former support may be overkill, and probably never used by front-end developers.

**Comment by philchalmers** [comment]
and yes `mirtCAT` is quite tricky to manage since `shiny` often has some clunky code/behaviour to work with. There probably should be a re-write done down the line that uses better javascript mechanics (like via `shinyjs`), and allow better modularity in setting up the GUI session in general (e.g., for fully-customized multistage testing), but finding enough dedicated time to do this is difficult.

**Comment by MagnusNordmo** [comment]
I agree with your view that an per-item basis for such a feature would be overkill. I would think that a consistent global behaviour throughout a test is what most people would want. I also love the idea of including javascript mechanics but acknowledge that this is a huge task. Please do not feel rushed.

**Comment by philchalmers** [comment]
I've set the default to now use the last selected response prior to the timer running out as the final answer. I think that's the most natural behaviour. Thinking about it pressing the `Next` button is really just a means-to-an-end, so the last observed response should be sufficient in a CAT session with timers. Let me know if the latest update is working on your end.

**Comment by MagnusNordmo** [comment]
I agree completely. Works like a charm! Terrific! I will let you know if anything comes up in testing.

**Comment by MagnusNordmo** [comment]
Noticed something right away. If I answer correctly on all three items, the last item is stored as a `0` in `scored_responses`. However, the answer is captured in `raw_responses`. 

```
df <- data.frame(Questions = c('First is correct','Third is correct','Second is correct'),
                 Options = matrix(c(1,2,3,4,5),ncol = 5,byrow = T),
                 Type = 'radio',
                 Timer = c(10,10,10),
                 Answer = c(1,3,2))

shinyGUI = list(forced_choice = F,authors = '')

results <- mirtCAT(df = df,shinyGUI = shinyGUI)

results$scored_responses

results$raw_responses
```

**Comment by philchalmers** [comment]
Ugh, good catch. It looks like old conflicting logical terms that was trying to set expired item times as scored to 0 automatically rather than the new 'whatever was left selected' form, and instead should only score a 0 when no response was provided at all (again, quite a reasonable behaviour IMO). Should be patched, thanks again for testing....there's a good number of things that interact in this area of development.

FYI, `forced_choice` is now auto set to FALSE when any timer is used (makes sense to do this automatically now).

**Comment by MagnusNordmo** [comment]
Incredible speed! It works great. Thanks!

**Comment by philchalmers** [comment]
Closed for now, but feel free to re-open if something comes up. Cheers.
