### ISSUE TITLE
Changing listener port and host?

### ISSUE THREAD

**Issue by whiteplastic** [philchalmers/mirtCAT#7]
Is there a way to change the IP/host and port that the application listens on? I know how to change this in shiny itself, but not fromt within mirtCAT.

**Comment by philchalmers** [comment]
This was undocumented and not completely supported before, but now it should be possible in all functions. Simply pass an additional `options = list(port = 7790)` or whatever to `mirtCAT()` or `createShinyGUI()` to tell shiny about additional arguments.

**Comment by whiteplastic** [comment]
Hmm, passing this directly to `mirtCAT()` does not work - `(options = list(port = 7790))` seems to be an unused argument. If I pass it to `createShinyGUI()` or add it to `guiList`, it seems to get ignored.

**Comment by philchalmers** [comment]
My apologies, I had some confusion regarding why `runApp()` and `shinApp()` had different input styles. Now everything should be wrapped inside of a `runApp()` call, and `createShinyGUI()` no longer accepts any arguments. See the help file for `createShinyGUI()` for an example of how this should be done. 

Regarding `mirtCAT()` itself the inputs are now the same, just pass arguments like `port = 8000` directly rather than wrapping them inside of a list. Sorry for the confusion, and thanks for being so persistent.
